version: "3.9"

services:
  front:
    restart: unless-stopped
    build: ./app
    ports:
      - "3000:3000"
    env_file:
      - .env
  back:
    restart: unless-stopped
    build: ./back
    ports:
      - "8080:8080"
    env_file:
      - .back.env